[workspace]
members = [
    "packages/cosmos",
    "packages/cosmos-bin",
]

[profile.dev]
# Disabling debug info speeds up builds a bunch,
# and we don't rely on it for debugging that much.
debug = 0
