[package]
name = "cosmos"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.25.0", features = ["full"] }
anyhow = "1.0.69"
tonic = { version = "0.8", features = [
    "channel",
    "tls",
    "tls-roots",
], default-features = false }
cosmos-sdk-proto = { version = "0.16.0", features = ["cosmwasm"] }
prost = "0.11.6"
prost-types = "0.11"
bech32 = "0.9.1"
bitcoin = "0.29.2"
hkd32 = { version = "0.7.0", features = ["bip39"] }
once_cell = "1.17.1"
rand = "0.8.5"
log = "0.4.17"
fs-err = "2.9.0"
serde = "1"
serde_json = "1"
chrono = "0.4"
hex = "0.4"
sha2 = "0.10"
reqwest = { version = "0.11.14", default-features = false, features = ["json"] }
base64 = "0.21"
parking_lot = "0.12"
clap = { version = "4", features = ["derive", "env"], optional = true }
bip39 = "2"
bb8 = "0.8.1"

[features]
clap = ["dep:clap"]

[dev-dependencies]
quickcheck = "1"
