[package]
name = "cosmos-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
clap_complete = "4"
anyhow = "1.0.69"
cosmos = { path = "../cosmos" }
tokio = { version = "1.25.0", features = ["full"] }
chrono = { version = "0.4.23", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
reqwest = { version = "0.11.14", default-features = false, features = [
    "rustls-tls",
    "json",
] }
futures = "0.3.26"
log = "0.4.17"
env_logger = "0.10.0"
regex = "1"
once_cell = "1.17.1"
fs-err = "2"
base64 = "0.21"

[dev-dependencies]
quickcheck = "1"

[[bin]]
name = "cosmos"
path = "src/main.rs"
