name: Build
on:
  push:
    branches: [develop, main]
    # Don't include paths here, we want to build on every push
  pull_request:
    paths:
      - "packages/**"
      - ".github/**"
  workflow_dispatch:

jobs:
  cosmos-bin:
    uses: fpco/reusable_workflows/.github/workflows/rust_build_lint_test.yml@rust
    with:
      toolchain: "1.70.0"
      binary: cosmos
      package: cosmos-bin
      build_version_location: "packages/build-version.txt"
    secrets:
      git_credential: "N/A"

