name: Relase
on:
  push:
    tags:
      - "*"

jobs:
  cosmos-bin:
    uses: fpco/reusable_workflows/.github/workflows/rust_build_lint_test.yml@rust
    with:
      toolchain: "1.65.0"
      binary: cosmos
      package: cosmos-bin
      build_version_location: "packages/build-version.txt"
    secrets:
      git_credential: "N/A"
  release:
    runs-on: ubuntu-latest
    needs: [cosmos-bin]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: cosmos
          path: .
      - uses: ncipollo/release-action@v1
        with:
          artifacts: cosmos
          tag: ${{ github.ref_name }}
